package com.hadrix.agriculture_craft;

import net.minecraft.network.chat.Component;
import net.minecraft.network.chat.MutableComponent;

/**
 * Translation <em>keys</em> for the mod, plus a small helper for turning them into
 * Components at runtime. Deliberately holds no English text: the copy lives in the
 * hand-authored partials under {@code assets/agriculture_craft/lang/default/} (interface.json,
 * tooltips.json), which {@link com.hadrix.agriculture_craft.datagen.AgricultureCraftLangMerger} merges
 * into the generated {@code en_us.json} during runData. Block, item and creative-tab
 * names are derived and generated by Registrate automatically.
 */
public class Lang {

    public static final String CREATIVE_TAB = "itemGroup." + AgricultureCraft.ID;
    public static final String GENERATOR_GENERATING = gui("agriculture_craft_generator.generating");
    public static final String KINETIC_CONSUMING = gui("agriculture_craft_kinetic.consuming");
    public static final String RPM = gui("rpm");
    public static final String SU = gui("su");

    private static String gui(String path) {
        return "gui." + AgricultureCraft.ID + "." + path;
    }

    public static MutableComponent translate(String key, Object... args) {
        return Component.translatable(key, args);
    }
}
